# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a5cbe3928caf97b8f519195a3d2a788c7a73240a7b9b2013c63ea46c308f6cfb50648c18a83e9c6e47c65d6073da4aebceba9f1137d50c7680458e65d2e3ec

test:
  secret_key_base: f432c6e9d13e4f88e6ea8ce262540214c4d0e7683614665f6fca893440982aa557bf9571c601f31fbc09a441c9c7bb7692748d9a3a120448f3b5f2503e1a4325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
